[package]
name = "example_using_structs"
version = "0.1.0"
authors = ["tatamiya <tamyuji1002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
